sso:
  name: "sso-auth-manager"
  server:
    login-url: http://sso.auth.com:8080
    sso-server-url: http://center.sso.auth.com:8081
    app-server-url: http://manager.sso.auth.com:8082
  client:
    id: 1002
    secret: ee538d43a74a052450a0cf56eae824a3
  h5-enabled: true
  url-patterns: ["*"]
  exclude-urls: ['/doc.html',"/v2/api-docs","/webjars/css/*","/webjars/js/*","/swagger-resources/*","/swagger-ui.html"]
  logout-path: "/logout"
  token-name-prefix: "sso-oauth2-token-"

server:
  port: 8082

spring:
  application:
    name: ssoManager
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.97.117:3306/sso?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: cx330
    password: miao123456
    hikari:
      # 连接池名
      pool-name: DataHikari
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10min）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 连接最大存活时间，0表示永久存活，默认180000（30min）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30s）
      connection-timeout: 30000
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 117.72.97.117
    port: 6379
    password: miao123456
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 5s


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0.0
    description: "单点登录管理系统接口文档"
    concat: 睡不醒的喵桑
    group:
      manager:
        api-rule: package
        api-rule-resources:
          - com.miao.sso.auth.authManager.controller